eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
spring:
  application:
    name: order
  rabbitmq:
    host: 47.95.119.164
    port: 5672
    username: root
    password: Qinfo20180507  
server:
  port: 8889
